name: Create PR to main

on:
  push:
    branches:
      - develop

jobs:
  git-pr-release:
    name: git-pr-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git-pr-release
        uses: bakunyo/git-pr-release-action@v1.4
        env:
          TZ: "Asia/Tokyo" # タイトルの日時を +9 にするため
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: .github/RELEASE_PULL_REQUEST_TEMPLATE.md
