name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    permissions:
      contents: write # for release-drafter/release-drafter to create a github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: heroku_deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # 秘匿鍵を預けるため、バージョンを固定しておく
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: hashlog # Must be unique in Heroku
          heroku_email: aiandrox7@gmail.com

      - name: Create Draft Release
        id: create_draft_release
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          #   config-name: my-config.yml
          disable-autolabeler: true
          publish: true
          # release の出力値
          id: true
          body: true
