name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    permissions:
      contents: write # for release-drafter/release-drafter to create a github release
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create Draft Release
        id: create_draft_release
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          #   config-name: my-config.yml
          disable-autolabeler: true

      - uses: actions/checkout@v3
        with:
          ref: main
      - name: heroku_deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # 秘匿鍵を預けるため、バージョンを固定しておく
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: hashlog # Must be unique in Heroku
          heroku_email: aiandrox7@gmail.com

      - uses: actions/checkout@v3 # default branch で実行されたイベントでないとトリガーしないので
        with:
          ref: develop
      - name: Publish Release
        uses: eregon/publish-release@v1
        with:
          release_id: ${{ steps.create_draft_release.outputs.id }}
