name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # for release-drafter/release-drafter to create a github release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: heroku_deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: hashlog # Must be unique in Heroku
          heroku_email: aiandrox7@gmail.com

      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: echo release note
        id: get_release_note
        run: |
          # 改行コードをエスケープする
          release_body='${{ steps.create_release.outputs.body }}'
          release_body=${release_body//$'\r\n'/\\n}
          release_body=${release_body//$'\n'/\\n}
          echo "::set-output name=body::$release_body"

      - name: Send Release Note
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": ":rocket: ${{ steps.create_release.outputs.published_at }} ${{ steps.create_release.outputs.name }} Released!\n${{ steps.create_release.outputs.html_url }}\n```${{ steps.get_release_note.outputs.body }}```",
              "unfurl_links": false
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  failure-notify:
    runs-on: ubuntu-latest
    needs: [release]
    if: failure()
    timeout-minutes: 5
    steps:
      - name: Send Failure
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": ":cry: Release Job Failure...\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
